# Generated by Django 4.1.5 on 2023-05-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_position_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlvote',
            name='county',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='controlvote',
            name='district',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
