# Generated by Django 4.1.5 on 2023-05-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_controlvote_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='county',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='district',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
