# Generated by Django 4.1.5 on 2023-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='citizenship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='residency_proof',
            field=models.FileField(upload_to='residency_proofs'),
        ),
    ]
