# Generated by Django 4.2.1 on 2023-06-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_remove_profile_residency_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('vote_datetime', models.DateTimeField(auto_now_add=True)),
                ('control_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.controlvote')),
            ],
        ),
    ]
