# Generated by Django 4.2.1 on 2023-06-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_voterecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteRecord',
        ),
    ]
